In [2]:
import numpy as np

In [8]:
A = np.array([[0,1,1,0],[1,0,1,0],[1,1,0,1],[0,0,1,0]])
A

array([[0, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 0]])

In [9]:
I = np.eye(A.shape[0])
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
A = A + I
A

array([[1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [0., 0., 1., 1.]])

In [13]:
D = np.sum(A, axis=1)
D

array([3., 3., 4., 2.])

In [16]:
D = np.diag(D)
D

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 2.]])

In [21]:
DD = np.power(np.sum(A,axis=1), -0.5)
DD
DD = np.diag(DD)
DD

array([[0.57735027, 0.        , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.        , 0.70710678]])

In [27]:
H = DD * A 
H = H * DD
H

array([[0.33333333, 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.5       ]])